// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_bHLTSCnbd0qNqZvMv9TN7G61dW9qFAQ',
    appId: '1:678142115752:web:46f9492289a9ba07a0679d',
    messagingSenderId: '678142115752',
    projectId: 'accelaid',
    authDomain: 'accelaid.firebaseapp.com',
    storageBucket: 'accelaid.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1UTKMuI_gJmuS9YAe2XbRFeg21eeIDsE',
    appId: '1:678142115752:android:3696bb0ea62f028aa0679d',
    messagingSenderId: '678142115752',
    projectId: 'accelaid',
    storageBucket: 'accelaid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25cYMViOgdHfdHHcpBvNypUr_ujGE_HI',
    appId: '1:678142115752:ios:f40ccd87dce1067da0679d',
    messagingSenderId: '678142115752',
    projectId: 'accelaid',
    storageBucket: 'accelaid.firebasestorage.app',
    iosBundleId: 'com.example.accelaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD25cYMViOgdHfdHHcpBvNypUr_ujGE_HI',
    appId: '1:678142115752:ios:f40ccd87dce1067da0679d',
    messagingSenderId: '678142115752',
    projectId: 'accelaid',
    storageBucket: 'accelaid.firebasestorage.app',
    iosBundleId: 'com.example.accelaid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_bHLTSCnbd0qNqZvMv9TN7G61dW9qFAQ',
    appId: '1:678142115752:web:9a2fff3129b54cc1a0679d',
    messagingSenderId: '678142115752',
    projectId: 'accelaid',
    authDomain: 'accelaid.firebaseapp.com',
    storageBucket: 'accelaid.firebasestorage.app',
  );
}
