// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzFU8Z5FgPmAUg3t9hKCw0gfHcFo16M4o',
    appId: '1:710392346049:web:8d60b8b160d10623442b40',
    messagingSenderId: '710392346049',
    projectId: 'exosuitapp',
    authDomain: 'exosuitapp.firebaseapp.com',
    storageBucket: 'exosuitapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaqIpgVy-CbmUPU14S3sepOvhqr9iVaJU',
    appId: '1:710392346049:android:677604cdd0abb346442b40',
    messagingSenderId: '710392346049',
    projectId: 'exosuitapp',
    storageBucket: 'exosuitapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8xAy_0taYzym3uEyhTcy5zlvv2ATjfJQ',
    appId: '1:710392346049:ios:a89b06d1206025fc442b40',
    messagingSenderId: '710392346049',
    projectId: 'exosuitapp',
    storageBucket: 'exosuitapp.firebasestorage.app',
    iosBundleId: 'com.example.workerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8xAy_0taYzym3uEyhTcy5zlvv2ATjfJQ',
    appId: '1:710392346049:ios:a89b06d1206025fc442b40',
    messagingSenderId: '710392346049',
    projectId: 'exosuitapp',
    storageBucket: 'exosuitapp.firebasestorage.app',
    iosBundleId: 'com.example.workerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzFU8Z5FgPmAUg3t9hKCw0gfHcFo16M4o',
    appId: '1:710392346049:web:11955b0e779c68c1442b40',
    messagingSenderId: '710392346049',
    projectId: 'exosuitapp',
    authDomain: 'exosuitapp.firebaseapp.com',
    storageBucket: 'exosuitapp.firebasestorage.app',
  );
}
